# Generated by Django 5.0.1 on 2024-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapidType', '0005_remove_testresult_text_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='text_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
