# Generated by Django 5.0.1 on 2024-03-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RapidType', '0006_testresult_text_type_alter_testresult_test_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextPrompt',
        ),
    ]
